services:
  gateway:
    container_name: shop_gateway_service_test
    build:
      context: .
      dockerfile: ./services/gateway/deploy/Dockerfile
      target: dev
    volumes:
      - ./go.work:/workspace/go.work
      - ./go.work.sum:/workspace/go.work.sum
      - ./shared:/workspace/shared
      - ./services/gateway:/workspace/services/gateway
    ports:
      - "${GATEWAY_EXTERNAL_PORT}:80"
    env_file:
      - ./services/gateway/.env
    depends_on:
      - auth-service
    restart: no

  auth-service:
    container_name: shop_auth_service_test
    build:
      context: .
      dockerfile: ./services/auth-service/deploy/Dockerfile
      target: dev
    volumes:
      - ./go.work:/workspace/go.work
      - ./go.work.sum:/workspace/go.work.sum
      - ./shared:/workspace/shared
      - ./services/auth-service:/workspace/services/auth-service
    ports:
      - "${AUTH_EXTERNAL_PORT}:8080"
    env_file:
      - ./services/auth-service/.env
    environment:
      - EMAIL_HOST=mailer
      - EMAIL_PORT=1025
      - EMAIL_USERNAME=""
      - EMAIL_PASSWORD=""
      - EMAIL_FROM="no-reply@shop.test"
      - EMAIL_SCIP_AUTH_AND_TLS=true
    depends_on:
      - database
      - mailer
    restart: no

  database:
    container_name: shop_database_test
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_EXTERNAL_PORT}:5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d/
      - pgdata_test:/var/lib/postgresql/data/pgdata
    restart: no

  mailer:
    container_name: shop_mailer_test
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: no


volumes:
  pgdata_test:
    driver: local